version: "3.9"

services:
  postgis:
    image: postgis-custom
    ports:
      - "5432:5432"
    volumes:
      - ./data/:/tmp/data
    networks:
       - postgis-network
    build:
      context: .
      dockerfile: Dockerfile-postgis
    env_file:
      - variables.env

  flask-app:
    image: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - postgis
    networks:
      - postgis-network
    build:
      context: .
      dockerfile: Dockerfile-app
    env_file:
      - variables.env

networks:
  postgis-network: