FROM postgis/postgis:15-3.3

# install qgis
RUN apt update -y && apt install -y gnupg software-properties-common && mkdir -m755 -p /etc/apt/keyrings \
    && apt install -y wget \
    && wget -O /etc/apt/keyrings/qgis-archive-keyring.gpg https://download.qgis.org/downloads/qgis-archive-keyring.gpg \
    && echo 'Types: deb deb-src' >> /etc/apt/sources.list.d/qgis.sources \
    && echo 'URIs: https://qgis.org/debian' >> /etc/apt/sources.list.d/qgis.sources \
    && echo 'Suites: bullseye' >> /etc/apt/sources.list.d/qgis.sources \
    && echo 'Architectures: amd64' >> /etc/apt/sources.list.d/qgis.sources \
    && echo 'Components: main' >> /etc/apt/sources.list.d/qgis.sources \
    && echo 'Signed-By: /etc/apt/keyrings/qgis-archive-keyring.gpg' >> /etc/apt/sources.list.d/qgis.sources \
    && apt update -y \
    && apt install -y qgis qgis-plugin-grass

ADD init_db.sh /docker-entrypoint-initdb.d/init_db.sh